### ISSUE TITLE
Necesitas actualizar para MD

### ISSUE THREAD

**Issue by AllMightHero** [BrunoSobrino/ShadowBotV3#21]
Ocupas actualizar el repositorio para poder usar el bot.

**Comment by BrunoSobrino** [comment]
Si, pero mis conocimientos no me dan para ello, usted sabe hacerlo?

**Comment by AllMightHero** [comment]
> Si, pero mis conocimientos no me dan para ello, usted sabe hacerlo?

ya intenté, la única manera es borrando el módulo de whatsapp md y aún así fallan algunas cosas.

**Comment by BrunoSobrino** [comment]
> > Si, pero mis conocimientos no me dan para ello, usted sabe hacerlo?
> 
> ya intenté, la única manera es borrando el módulo de whatsapp md y aún así fallan algunas cosas.

Si te refieres a los comandos es posible que fallen porque tienen puesto como requerimiento baileys, seria cambiarlo por el nuevo modulo md, hay forma de que pudieras prestarme tu edición para ver como puedo solucionar esos errores? te lo agradecería mucho
